---
# Base setup
- include_tasks: base.yaml

# Shell
- include_tasks: shell.yaml

# SSH
- include_tasks: ssh.yaml

# OMZ
- include_tasks: omz.yaml

# NVM
- include_tasks: nvm.yaml

# Create a workspace directory for projects
- name: Create workspace directory
  file:
    path: /home/{{ ansible_user }}/workspace
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'
