# Install NVM (Node Version Manager)
- name: Install NVM
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  args:
    creates: /home/{{ ansible_user }}/.nvm/nvm.sh
  environment:
    HOME: /home/{{ ansible_user }}
    USER: '{{ ansible_user }}'
  become: false

# # Add NVM to the user's shell profile
# - name: Update .zshrc
#   ansible.builtin.lineinfile:
#     path: "/home/{{ ansible_user }}/.zshrc"
#     insertafter: EOF
#     line: |
#       ## NVM
#       export NVM_DIR="$HOME/.nvm"
#       [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#       [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Install the latest Node.js LTS version using NVM if not already an LTS of the same major version
- name: Install latest Node.js LTS
  shell: >
    . /home/{{ ansible_user }}/.nvm/nvm.sh &&
    if ! nvm ls --no-colors | grep -q "lts/*"; then
      nvm install --lts;
    fi
  args:
    executable: /bin/zsh
    creates: /home/{{ ansible_user }}/.nvm/versions/node
  environment:
    HOME: /home/{{ ansible_user }}
    USER: '{{ ansible_user }}'
