# Install Powerline fonts
- include_tasks: fonts.yaml

# required by the OMZ plugin zsh-interactive-cd
- name: Install fzf (command-line fuzzy finder)
  become: true
  ansible.builtin.package:
    state: present
    name: fzf

- name: Download ohmyzsh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: "/tmp/install-omz.sh"
    mode: '0755'

- name: Install ohmyzsh
  ansible.builtin.shell: "RUNZSH=no CHSH=no KEEP_ZSHRC=yes /tmp/install-omz.sh"
  args:
    creates: "/home/{{ ansible_user }}/.oh-my-zsh"
  become: false
 
- name: Install zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    depth: 1
 
- name: Install zsh-completions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-completions
    depth: 1
 
- name: Install zsh-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/{{ ansible_user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    depth: 1
