# Install Zsh
- name: Install Zsh
  apt:
    name: zsh
    state: present
    
# Set Zsh as the default shell for the user
- name: Set Zsh as default shell
  user:
    name: '{{ ansible_user }}'
    shell: /usr/bin/zsh

# Copy the new initial .zshrc file from the template folder if it doesn't already exist on the remote
- name: Copy new initial .zshrc file from template
  template:
    src: ../../templates/zshrc
    dest: /home/{{ ansible_user }}/.zshrc
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0644'
    force: no
