# Set a list of public keys to be added to the authorized_keys file for the development user.
- name: Define ssh public keys for remote user to accept
  set_fact:
    authorized_keys: "{{ config.authorized_keys | default({}) }}"

- name: Debug authorized_keys
  debug:
    var: authorized_keys

# Set up SSH keys for the remote user by iterating over authorized_keys
- name: Set up SSH keys for remote user
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', item.value) }}"
  loop: "{{ authorized_keys | dict2items }}"
