---
# Setup Docker

- name: Check If Docker Is Installed
  command: docker --version
  register: docker_valid
  ignore_errors: yes

- name: Debug Docker Output
  debug:
    var: docker_valid

- name: Install Docker
  when: docker_valid.failed
  become: yes
  args:
    executable: /bin/zsh
  shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
    sudo usermod -aG docker $USER
    sudo systemctl enable docker
    sudo systemctl start docker

- name: Adding existing user '{{ ansible_user }}' to group docker
  when: docker_valid.failed
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes
